### ISSUE TITLE
[Greenwich and Stratford  change to Cheshire and Stratford]

### ISSUE THREAD

**Issue by js2k2000** [TomGoBravo/tourist-with-flask#10]
## Place

[ USA Connecticut   Cheshire and Stratford  ]

## Club(s)

[Barnacles
    
    Contact: ctbarnacles@gmail.com
    meetup    https://www.meetup.com/Barnacles-Underwater-Hockey/
    facebook  https://www.facebook.com/BarnaclesUnderwaterHockey/

    Practice: Sunday 9am-11:15am at the Cheshire Community Pool 520 South Main Street, Cheshire, CT 06410
    Practice: Thursday 7:30pm-9pm at the Stratford YMCA, 3045 Main St, Stratford, CT
]

## Pool(s)

[ replace Greenwich with Cheshire

Open Cheshire Community Pool   520 S Main St, Cheshire, CT 06410

https://www.google.com/maps/place/Cheshire+Community+Pool/@41.4868228,-72.9011089,15z/data=!4m5!3m4!1s0x0:0x2e6f3489b7e53144!8m2!3d41.4868228!4d-72.9011089

in google maps
]

**Comment by TomGoBravo** [comment]
Hi @js2k2000  Thank you for the update. Please re-open if you'd like more changes to https://pucku.org/tourist/place/greenwichandstratfordcon

**Comment by js2k2000** [comment]
1. On page https://pucku.org/tourist/place/greenwichandstratfordcon
Greenwich needs to be replaced with Cheshire from heading, I'll assume that will also make same correction on List All page.

**Comment by TomGoBravo** [comment]
Fixed. Thank you for checking it.
