### ISSUE TITLE
Update the website and timings for the U of I

### ISSUE THREAD

**Issue by adadarohan** [TomGoBravo/tourist-with-flask#122]
## Place

https://pucku.org/tourist/place/urbanachampaignillinois

## Club(s)

University of Illinois Underwater Hockey Club
Website - https://sites.google.com/view/illinoisuwh/
Practice - Tuesdays and Thursdays, 8:30pm to 10pm at the ARC

## Pool(s)

Existing Location is correct

**Comment by TomGoBravo** [comment]
Thank you for the update! What days do you play?https://sites.google.com/view/illinoisuwh/calendar says  Tuesday and Thursday from 7-8:30 PM at the ARC. I'm guessing it makes sense to remove Carrie's contact info and leave IllinoisUWH@gmail.com

**Comment by adadarohan** [comment]
Oops, I forgot to add the days. You're right, it's Tuesday and Thursdays, but the timing is 8:30 to 10pm. I'll update our website soon, and I've edited my original message.

Yes, that would be great! Our members graduate every 4 years so it's hard to have a consistent contact.

**Comment by TomGoBravo** [comment]
Super, I've updated https://pucku.org/tourist/place/urbanachampaignillinois
Let me know if you see anything else to update.
