### ISSUE TITLE
UDF Underwater Hockey Club

### ISSUE THREAD

**Issue by udfkorea** [TomGoBravo/tourist-with-flask#17]
## Place

[Daejeon, South Korea]

## Club(s)

[
UDF Underwater Hockey Club. June Hyuk Lee at chacony@naver.com or +821091213404 

http://cafe.naver.com/udfreediving

Wednesday nights @ 6:30PM
]

## Pool(s)

[
Youngun international swimming pool,
138 Dongbu-ro, Yongun-dong, Dong-gu, Daejeon, South Korea

https://goo.gl/maps/2CzoPoShJTkWyvoL7
]

**Comment by TomGoBravo** [comment]
Hi June, thank you for the report. I created https://pucku.org/tourist/place/daejeon
Please let me know if you'd like any changes made. Sorry it took so long to update this.
