### ISSUE TITLE
[ Underwater Hockey Korea - Seoul / Seongnam ]

### ISSUE THREAD

**Issue by edcat** [TomGoBravo/tourist-with-flask#18]
## Place
[ Seoul, South Korea ]

## Club(s)
[ Open chat : https://open.kakao.com/o/gUOqiRP   (English ok) ]
[ Contact  takion@hotmail.com for more information                 ]
[ Every Saturday 09:00~12:00 : subject to change ]

## Pool(s)
[ Seongnam Sportscomplex diving pool - a.k.a. Aqualine ]
[ https://goo.gl/maps/Y7UpW3B72rDdXvRg6 ]

**Comment by edcat** [comment]
Please feel free to ping me for any more information needed 👍

**Comment by edcat** [comment]
Pool map 
https://goo.gl/maps/Y7UpW3B72rDdXvRg6

**Comment by TomGoBravo** [comment]
Hi @edcat , thank you for the report. Sorry it took me so long to notice it, I had failed to enable notifications for new issues.
I created https://pucku.org/tourist/place/seoulkr
Please let me know if you'd like anything changed.
See you at the bottom,
Tom
