### ISSUE TITLE
to add: Germany, Berlin 

### ISSUE THREAD

**Issue by Su-Mi** [TomGoBravo/tourist-with-flask#19]
## Place

Berlin, Germany

## Club(s)

Sporttaucher Berlin 
http://berlinuwh.wordpress.com/
https://www.facebook.com/groups/berlinuwh/ 
berlinuwh@gmail.com 

## Pool(s)

Sport- und Lehrschwimmhalle Schöneberg
Sachsendamm 11, 10829 Berlin

https://www.google.com/maps/place/Sports+and+teaching+swimming+pool+Sch%C3%B6neberg/@52.4762791,13.3541132,17z/data=!3m1!4b1!4m5!3m4!1s0x47a850135bc9a5f9:0x790ada61e0037217!8m2!3d52.4762791!4d13.3563019

**Comment by TomGoBravo** [comment]
Hi @Su-Mi ,
Thank you for the report. Sorry it took my so long to create https://pucku.org/tourist/place/berlin
I've now enabled notifications when issues are created so I can respond more quickly.
Let me know if you'd like any more changes.
Tom
