### ISSUE TITLE
Club Puck details need updating

### ISSUE THREAD

**Issue by hockeybrigit** [TomGoBravo/tourist-with-flask#20]
Club Puck
San Francisco Bay Area
Club contact- Ben Phipps, swimmerscantrun@yahoo.com
Hockey Tu and Thu 8-930pm
Burgess Park Pool- 501 Laurel St, Menlo Park, CA 94025
Park in the parking lot at Laurel St. and Burgess Dr.

**Comment by TomGoBravo** [comment]
Hey Brigit, sorry it took me so long to see this but https://pucku.org/tourist/place/sanfranciscocalifornia is updated now.
