### ISSUE TITLE
Map should be 225 SE Avery St, Newport, OR 97365, one map is the old location, another is the east coast.

### ISSUE THREAD

**Issue by Anaerobicaqua** [TomGoBravo/tourist-with-flask#21]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place

[Link to place at pucku.org or name of relevant country/region/city you'd like to add or update.]
[Optional: Information about hockey in this place that is not specific to a club]

## Club(s)

[Information about club(s) to update. Ideally every club is listed with a person's name, email and phone number. Links to websites or groups used by the club are also useful.]

## Pool(s)

[Pools are listed with a latitude,longitude pin to the entrance location on a map. Please try to provide it. A link to Google Maps works well.]

**Comment by TomGoBravo** [comment]
Hey @Anaerobicaqua, sorry for the big delay. I finally fixed https://pucku.org/tourist/place/newportoregon
Thank you for the report and let me know if you see anything else amiss.
