### ISSUE TITLE
Editor Access ??

### ISSUE THREAD

**Issue by steves2002** [TomGoBravo/tourist-with-flask#22]
Hi Tom,

Just wanting to get access to update some the Aussie/QLD club details.

See you on the bottom,
Steve

**Comment by TomGoBravo** [comment]
Hi Steve, sorry for the massive delay. I'm trying to catch up after a lot of time away. I don't see your github account in the pucku.org user list. You need to login once before I can grant editor access. See https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide

**Comment by steves2002** [comment]
Hi Tom,

I recall when I sent this request, so it must’ve been a while ago!!  Anyway I have now a GitHub account and signed in to pucku as steves2002, so hopefully that is all I need to do from my end.  Let me know if there is anything else.

***@***.***

Thanks,
Steven


Steven Keegel
Senior Solutions Consultant
***@***.******@***.***>
Mobile: +61 402 051 520
Pronto Software Limited
Level 1, 189 Coronation Drive, Milton, QLD 4064, Australia
www.pronto.net<https://www.pronto.net>
+61 7 3377 1177
Twitter: @ProntoSoftware<https://twitter.com/ProntoSoftware>
LinkedIn: pronto-software<https://www.linkedin.com/company/pronto-software>


<https://www.pronto.net/><https://pronto.net/>[cid:ProntoSoftwarelogo_ongrey169x55_7111f6c4-4990-4648-97b4-9f4320875abd.gif]<https://www.pronto.net/><https://www.pronto.net/>


---Legal Notice---
The email message and any attachments are confidential and subject to copyright. If you are not the intended recipient, any use, interference with, disclosure or copying of this material is unauthorised and prohibited. No part may be reproduced, adapted or transmitted without the written permission of the copyright owner. If you have received this email in error, please immediately advise the sender by return email and delete the message from your system. Before opening or using attachments, check for viruses and defects. Our liability is limited to re-supplying any affected attachments.

**Comment by TomGoBravo** [comment]
You have edit access now. Let me know if you have any questions.
