### ISSUE TITLE
[Update the UWH contact for Hong Kong]

### ISSUE THREAD

**Issue by hkuwha** [TomGoBravo/tourist-with-flask#23]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place

[https://www.facebook.com/HKUWHA/]
[https://www.meetup.com/Hong-Kong-Underwater-Hockey-Association/]

## Club(s)

[The Hong Kong Underwater Hockey Association.  Contact person: Mr. Henry Chan, Whatsapp: (+852) 9088 7303, email: hkuwha@gmail.com]

*Please note the club originally on your site, under Richard is not longer active.  I may pass Richard's contact to you for confirmation if needed. 

## Pool(s)

[Fridays: Whampoa Pool from 20:15 to 22:15
Tuesdays: Wah Yan Pool from 19:30 to 21:30

Please contact Henry for latest information]

**Comment by TomGoBravo** [comment]
Sorry for the massive delay, I'm finally catching up on field reports. I added your club and removed the old information. Please take a look at https://pucku.org/tourist/place/hongkongtown and reopen this issue if you'd like further changes.

**Comment by hkuwha** [comment]
Thanks very much for updating!
It's also nice that you've placed the line saying it's as updated to July
21 and they should contact me directly for latest info.
Coz we do have different time and venue for summer and winter.

Anyway, your work and effort is much appreciated and hope to meet you soon
underwater!

Cheers,
Henry Chan



*香港水底曲棍球協會*
*Hong Kong Underwater Hockey Association *
*Website:* https://www.facebook.com/HKUWHA
*Facebook Group: *https://www.facebook.com/groups/UWHHK
*Meetup Group:*
http://www.meetup.com/Hong-Kong-Underwater-Hockey-Association/
