### ISSUE TITLE
[Add short description such as name of place to update]

### ISSUE THREAD

**Issue by phil-roy** [TomGoBravo/tourist-with-flask#24]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place

https://www.pucku.org/tourist/place/sherbrookequbec

## Club(s)

Site update: https://www.facebook.com/hsmSherbrooke (http://www.hsmsherbrooke.org/ no longer valid)
The email info@hsmsherbrooke.org is no longer valid, we now use the messenger of the facebook page

## Pool(s)

Current info is still correct!

**Comment by TomGoBravo** [comment]
Sorry for the big delay. I'm finally catching up and updated https://www.pucku.org/tourist/place/sherbrookequbec
Please reopen this or make a new issue if you'd like more changes.
