### ISSUE TITLE
Green Bay Wisconsin  https://pucku.org/tourist/place/greenbaywisconsin

### ISSUE THREAD

**Issue by petercovach** [TomGoBravo/tourist-with-flask#25]
I would be interested in becoming an editor of the page.

## Place
https://pucku.org/tourist/place/greenbaywisconsin

## Club(s)

Contact:  Peter Covach at 920-328-5436
Practice:  Tuesdays 6:45P-8:30P or as marked on the meetup site.
https://www.meetup.com/green-bay-underwater-hockey/

## Pool(s)

The Kroc Community Center
https://www.google.com/maps/place/The+Salvation+Army+Ray+and+Joan+Kroc+Corps+Community+Center/@44.481603,-87.9817462,17z

**Comment by TomGoBravo** [comment]
Peter, it looks like Chris took care of this edit last month. I've granted you edit access so you make future changes yourself (see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide). Let me know if you have any questions.
