### ISSUE TITLE
Add new Irish UWH team to Site (Limerick)

### ISSUE THREAD

**Issue by cgall91** [TomGoBravo/tourist-with-flask#30]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place

[ Ireland/Limerick/Limerick City ]
[ Newly founded club, training weekly throughout the winter months. Tourists welcome and newbie sessions every month]

## Club(s)

[ Club name: Underwater Hockey Limerick 
Contact Information: Chris, email underwaterhockey.limerick@gmail, or reach out on our social media accounts 
Facebook: https://www.facebook.com/UWHLimerick
Instagram:  https://www.instagram.com/underwaterhockeylimerick/  ]

## Pool(s)

[ Practise Location: UL Arena Pool, Castletroy, Limerick. 
Post Code: V94 X9VK 
Google maps Link: https://goo.gl/maps/Wp1TTSfuQ2K8HpBS8
Practise time: Tuesdays 8pm- 10pm ]

**Comment by cgall91** [comment]
Absolutely amazing work putting this all together

**Comment by TomGoBravo** [comment]
Thank you for the update. Let me know if you'd like any changes to https://pucku.org/tourist/place/limerick
