### ISSUE TITLE
[Add new Irish UWH team to Site (Belfast)]

### ISSUE THREAD

**Issue by cgall91** [TomGoBravo/tourist-with-flask#31]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place

[Ireland/Antrim/Belfast]
[Established in 2014 Queens Sinking Sheep Underwater Hockey offers a strong and competitive setting for travelling UWH players. QUB sends teams to the BOA students nationals, take parts in the BOA nationals and several other European tournaments to keep their skills sharp. ]

## Club(s)

[Laura, email underwaterhockey@qub.ac.uk, preferably contact us on instagram @qub_uwh
https://www.facebook.com/QUBunderwaterhockey]

## Pool(s)

[Practice times: Monday 8pm-9:30pm
Queen's Sport Stranmillis Gardens, Belfast BT9 5EX, UK PEC https://www.google.com/maps/place/Queen's+PEC,+Stranmillis+Gardens,+Belfast+BT9+5EX,+UK/@54.5807975,-5.9317872,17z/data=!3m1!4b1!4m5!3m4!1s0x486108e5f60a7d69:0xdc4a2c99f5b8bf36!8m2!3d54.5807975!4d-5.9295985]

**Comment by TomGoBravo** [comment]
@cgall91 Thank you for the update! I created https://pucku.org/tourist/place/belfastie
Let me know if you'd like more changes.
