### ISSUE TITLE
UWHBern 

### ISSUE THREAD

**Issue by Silion1867** [TomGoBravo/tourist-with-flask#39]
## Place

https://pucku.org/tourist/place/bernbern

## Club(s)
UWHBern
Website: uwhbern.ch
Training sessions: Tuesday evening

Training session time and places changes with season:
Summer (May-September), in Worb, Tuesday 19:00 - 20:00
Winter (October-April), in Melchenbühl, Tuesday 20:00 - 21:00

## Pool(s)
Summer pool: 
Worb, Wislepark 
46.92614557191153, 7.562530451513532
https://www.google.com/maps/place/Wislepark/@46.9261274,7.5619501,18.5z/data=!4m5!3m4!1s0x478e342d18aaa4c5:0xcb776082e8c58111!8m2!3d46.926118!4d7.562606

Winter pool:
Schwimmbad Melchenbühl
46.93754512318368, 7.495709342344327
https://www.google.com/maps/place/Schwimmbad+Melchenb%C3%BChl/@46.9374755,7.4952507,19z/data=!4m5!3m4!1s0x478e37b3b40ec1dd:0xa3fb57e819a6bba1!8m2!3d46.9375755!4d7.4956418

**Comment by TomGoBravo** [comment]
Thank you for the report! I've updated https://pucku.org/tourist/place/bernbern
Please reopen this issue if I missed something.
