### ISSUE TITLE
UWH in Romont

### ISSUE THREAD

**Issue by Silion1867** [TomGoBravo/tourist-with-flask#40]
## Place
https://pucku.org/tourist/place/ch
Country: Switzerland
Region: Fribourg
City: Romont

## Club(s)
Information contact : julien.comes@hockeysub.ch
Training sessions : Monday 20:30 - 21:30

## Pool(s)
Pool in Épicentre Glâne
46.68695913037666, 6.912205453002633 
https://www.google.com/maps/place/Epicentre+Gl%C3%A2ne/@46.6870086,6.9110902,18.5z/data=!4m5!3m4!1s0x478e7ffaac828567:0x2938cf8bf3cd73c8!8m2!3d46.6869876!4d6.9121941

**Comment by TomGoBravo** [comment]
Thank you for the report! So far I've been putting Swiss cities directly in https://pucku.org/tourist/place/ch so I did the same for https://pucku.org/tourist/place/chromont instead of making a page for the Canton de Fribourg. Let me know if something else looks better to you.
