### ISSUE TITLE
UWH Copenhagen

### ISSUE THREAD

**Issue by mebrooks** [TomGoBravo/tourist-with-flask#45]
## Place

Country: Denmark
City: Copenhagen

## Club(s)

Contact: Mollie Brooks cphuwh@gmail.com
Training: Wednesdays at 20:15 if we can get at least 4 players.

## Pool(s)

Available upon request

**Comment by TomGoBravo** [comment]
Thank you for the report! Denmark was accidentally not in the list of countries but was on https://pucku.org/tourist/map
I marked the club as active.
Let me know if you'd like any further changes to https://pucku.org/tourist/place/denmark

**Comment by mebrooks** [comment]
Thanks for your excellent work! We would like to also announce that we have Saturday practices 15:40-18:00.

**Comment by TomGoBravo** [comment]
Nice! I've updated https://pucku.org/tourist/place/denmark
