### ISSUE TITLE
CAMO (Montréal, Québec)

### ISSUE THREAD

**Issue by rngadam** [TomGoBravo/tourist-with-flask#46]
## Place
https://pucku.org/tourist/place/montrealqubec

## Club(s)

CAMO Hockey Sous-Marin

As of 2023

https://www.facebook.com/groups/310207872348080/
Contact: Joseph Ravoahangy at Camo_Underwater@hotmail.com
Practices: 
Tuesday 20h30-22h30 and Friday 20h00-22h30,

## Pool(s)

Piscine Joseph-Charbonneau
https://maps.app.goo.gl/XcvzWM8iyrPSffbLA

**Comment by TomGoBravo** [comment]
Thank you for the report! I updated. https://pucku.org/tourist/place/montrealqubec
Let us know if you'd like further changes.
