### ISSUE TITLE
Brampton Ontario Canada

### ISSUE THREAD

**Issue by JohnFlorian** [TomGoBravo/tourist-with-flask#67]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place

[Brampton, Ontario, Canada]
[Weekly Pickup Underwater Hockey Tuesday Evenings 9:30-10:30 pm]

## Club(s)

[John Florian   johnlflorian@outlook.com   647-988-7513 https://www.facebook.com/photo/?fbid=10222177623562769&set=p.10222177623562769]

## Pool(s)

[Earnscliff Recreation Center, 44 Eastbourne Drive, Brampton Ontario  43.72355185655053, -79.69947978945015 P8F2+86 Brampton, Ontario]

**Comment by JohnFlorian** [comment]
Club should be "Brampton UWH" with the contact information as shown above.

**Comment by TomGoBravo** [comment]
Thank you for the report John! I updated https://pucku.org/tourist/place/bramptonontario
Let me know if you can help update anything else on the UWHT.

**Comment by JohnFlorian** [comment]
Thanks for your help!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JohnFlorian** [comment]
Hi Tom
I left a message regarding Brampton Pool Time Change:

https://pucku.org/tourist/place/bramptonontario

we now meet Tuesdays from 8pm to 9pm, same venue

Also, can you please help James Adams in Tampa, FL?
https://www.facebook.com/groups/1690070584567930/posts/3477777082463929/
He is trying to put his organization on the map.

thanks
John
647-988-7513

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
