### ISSUE TITLE
Belgium --> Sint-Pieters-Leeuw-->Zuunse Karpers 

### ISSUE THREAD

**Issue by jeremycoppey** [TomGoBravo/tourist-with-flask#9]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Place
Belgium, Sint-Pieters-Leeuw/Halle

[Link to place at pucku.org or name of relevant country/region/city you'd like to add or update.]
[Optional: Information about hockey in this place that is not specific to a club]

## Club(s)
Zuunse karpers
Steven De Laat
uwh.spl@gmail.com
www.zuunsekarpers.be
www.facebook.com/ZuunseKarpers
[Information about club(s) to update. Ideally every club is listed with a person's name, email and phone number. Links to websites or groups used by the club are also useful.]

## Pool(s)
pool location:
Wildersportcomplex 
Sportlaan 11
1600 Sint-Pieters-Leeuw
50°47'58.8"N 4°17'10.3"E
https://www.google.com/maps/place/50%C2%B047'58.8%22N+4%C2%B017'10.3%22E/@50.7996777,4.2851087,18z/data=!3m1!4b1!4m9!1m2!2m1!1swildersport+sint+pieters+leeuw!3m5!1s0x0:0x0!7e2!8m2!3d50.7996762!4d4.2862032
and a second training location 
Nederhem 35, 1500 Halle
50°44'18.6"N 4°14'32.8"E
https://www.google.com/maps/place/50%C2%B044'18.6%22N+4%C2%B014'32.8%22E/@50.7384878,4.2418888,19z/data=!3m1!4b1!4m13!1m6!3m5!1s0x0:0xa8b764c1158cdbe4!2sHallebad+Sportoase!8m2!3d50.7382547!4d4.2427201!3m5!1s0x0:0x0!7e2!8m2!3d50.7384866!4d4.2424364
[Pools are listed with a latitude,longitude pin to the entrance location on a map. Please try to provide it. A link to Google Maps works well.]

**Comment by TomGoBravo** [comment]
@jeremycoppey Thank you for the update!
I added https://pucku.org/tourist/place/sintpietersleeuwhalle
Please re-open this if you see a problem.
