### ISSUE TITLE
[Suzhou]

### ISSUE THREAD

**Issue by laoyazi1998** [TomGoBravo/tourist-with-flask#97]
> Thank you for contributing new information to the Underwater Hockey Tourist
> Please replace the items in [....] with the requested information, delete this text and click `Submit new issue`.
> An editor will add your update to the site soon. To learn about editing please see https://github.com/TomGoBravo/tourist-with-flask/wiki/Editor-guide.

## Suzhou

[Link to place at pucku.org or name of relevant country/region/city you'd like to add or update.]
[Optional: Information about hockey in this place that is not specific to a club]

## 
Max Zhang +86-15295618057
Email: 387669632@qq.com
Practice on Saturday Morning and Sunday Morning 7:00-9:00

[Information about club(s) to update. Ideally every club is listed with a person's name, email and phone number. Links to websites or groups used by the club are also useful.]

## Pool(s)

[Pools are listed with a latitude,longitude pin to the entrance location on a map. Please try to provide it. A link to Google Maps works well.]

**Comment by TomGoBravo** [comment]
Hi @laoyazi1998 ! I created https://pucku.org/tourist/place/suzhou
Please take a look and let me know if you see anything that can be updated or improved on the site. I saw the comments added to the China page. Comments are only visible to site editors, to discourage spam.
